# Generated by Django 4.2.5 on 2023-09-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routinedetail',
            name='time',
            field=models.CharField(max_length=11),
        ),
    ]
